version: 2
jobs:
   build:
     docker:
       - image: circleci/java:latest
     steps:
       - checkout
       - run: echo "hello world"
dependencies:
    override:
        - sudo pip install awscli
deployment:
  prod:
    branch: master
    commands:
      - aws s3 sync /home/ubuntu/BellMeadowsHOA s3://belmeadowshoa --delete
      
